stages:
  - validate
  - build

default:
  image: alpine:latest

validate-job:
  stage: validate
  script:
    - echo "OK"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never

lint-job:
  stage: validate
  image: node:22-alpine
  script:
    - echo "Lint"
  rules:
    - changes:
        - frontend/**/*
        - package.json
      when: always
    - when: never

build-job:
  stage: build
  script:
    - echo "Build"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never
