FROM postgres:16-alpine

COPY infra/scripts/init-db.sql /docker-entrypoint-initdb.d/01-init-db.sql
COPY infra/scripts/seed.sql /docker-entrypoint-initdb.d/02-seed.sql

RUN chmod 644 /docker-entrypoint-initdb.d/*.sql
