version: '3.8'

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: tissage-runner
    restart: unless-stopped
    environment:
      - TZ=Indian/Antananarivo
    volumes:
      - runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tissage-net
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  runner_config:

networks:
  tissage-net:
    external: true
