/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourismRouteImport } from './routes/tourism'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtisansRouteImport } from './routes/artisans'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ArtisanIdRouteImport } from './routes/artisan.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedLivreurRouteRouteImport } from './routes/_authenticated/livreur/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedLivreurIndexRouteImport } from './routes/_authenticated/livreur/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedOrderIdRouteImport } from './routes/_authenticated/order.$id'
import { Route as AuthenticatedLivreurFinaliserRouteImport } from './routes/_authenticated/livreur/finaliser'
import { Route as AuthenticatedDashboardShippingRouteImport } from './routes/_authenticated/dashboard/shipping'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardPromotionsRouteImport } from './routes/_authenticated/dashboard/promotions'
import { Route as AuthenticatedDashboardProductsRouteImport } from './routes/_authenticated/dashboard/products'
import { Route as AuthenticatedDashboardPayoutsRouteImport } from './routes/_authenticated/dashboard/payouts'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated/dashboard/orders'
import { Route as AuthenticatedDashboardB2bRouteImport } from './routes/_authenticated/dashboard/b2b'
import { Route as AuthenticatedArtisanRevenusRouteImport } from './routes/_authenticated/artisan/revenus'
import { Route as AuthenticatedArtisanQrCodeRouteImport } from './routes/_authenticated/artisan/qr-code'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminShippingRouteImport } from './routes/_authenticated/admin/shipping'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminPaiementsRouteImport } from './routes/_authenticated/admin/paiements'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminHubsRouteImport } from './routes/_authenticated/admin/hubs'
import { Route as AuthenticatedAdminCronRouteImport } from './routes/_authenticated/admin/cron'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedClientFactureIdRouteImport } from './routes/_authenticated/client/facture.$id'

const TourismRoute = TourismRouteImport.update({
  id: '/tourism',
  path: '/tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisansRoute = ArtisansRouteImport.update({
  id: '/artisans',
  path: '/artisans',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanIdRoute = ArtisanIdRouteImport.update({
  id: '/artisan/$id',
  path: '/artisan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivreurRouteRoute =
  AuthenticatedLivreurRouteRouteImport.update({
    id: '/livreur',
    path: '/livreur',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivreurIndexRoute =
  AuthenticatedLivreurIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLivreurRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedOrderIdRoute = AuthenticatedOrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivreurFinaliserRoute =
  AuthenticatedLivreurFinaliserRouteImport.update({
    id: '/finaliser',
    path: '/finaliser',
    getParentRoute: () => AuthenticatedLivreurRouteRoute,
  } as any)
const AuthenticatedDashboardShippingRoute =
  AuthenticatedDashboardShippingRouteImport.update({
    id: '/shipping',
    path: '/shipping',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardPromotionsRoute =
  AuthenticatedDashboardPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardProductsRoute =
  AuthenticatedDashboardProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardPayoutsRoute =
  AuthenticatedDashboardPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardB2bRoute =
  AuthenticatedDashboardB2bRouteImport.update({
    id: '/b2b',
    path: '/b2b',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedArtisanRevenusRoute =
  AuthenticatedArtisanRevenusRouteImport.update({
    id: '/artisan/revenus',
    path: '/artisan/revenus',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArtisanQrCodeRoute =
  AuthenticatedArtisanQrCodeRouteImport.update({
    id: '/artisan/qr-code',
    path: '/artisan/qr-code',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminShippingRoute =
  AuthenticatedAdminShippingRouteImport.update({
    id: '/shipping',
    path: '/shipping',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaiementsRoute =
  AuthenticatedAdminPaiementsRouteImport.update({
    id: '/paiements',
    path: '/paiements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminHubsRoute = AuthenticatedAdminHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCronRoute = AuthenticatedAdminCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedClientFactureIdRoute =
  AuthenticatedClientFactureIdRouteImport.update({
    id: '/client/facture/$id',
    path: '/client/facture/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/artisans': typeof ArtisansRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/logistics': typeof LogisticsRoute
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/tourism': typeof TourismRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/livreur': typeof AuthenticatedLivreurRouteRouteWithChildren
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/cron': typeof AuthenticatedAdminCronRoute
  '/admin/hubs': typeof AuthenticatedAdminHubsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/shipping': typeof AuthenticatedAdminShippingRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/artisan/qr-code': typeof AuthenticatedArtisanQrCodeRoute
  '/artisan/revenus': typeof AuthenticatedArtisanRevenusRoute
  '/dashboard/b2b': typeof AuthenticatedDashboardB2bRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsRoute
  '/dashboard/promotions': typeof AuthenticatedDashboardPromotionsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/shipping': typeof AuthenticatedDashboardShippingRoute
  '/livreur/finaliser': typeof AuthenticatedLivreurFinaliserRoute
  '/order/$id': typeof AuthenticatedOrderIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/livreur/': typeof AuthenticatedLivreurIndexRoute
  '/client/facture/$id': typeof AuthenticatedClientFactureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/artisans': typeof ArtisansRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/logistics': typeof LogisticsRoute
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/tourism': typeof TourismRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/cron': typeof AuthenticatedAdminCronRoute
  '/admin/hubs': typeof AuthenticatedAdminHubsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/shipping': typeof AuthenticatedAdminShippingRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/artisan/qr-code': typeof AuthenticatedArtisanQrCodeRoute
  '/artisan/revenus': typeof AuthenticatedArtisanRevenusRoute
  '/dashboard/b2b': typeof AuthenticatedDashboardB2bRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsRoute
  '/dashboard/promotions': typeof AuthenticatedDashboardPromotionsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/shipping': typeof AuthenticatedDashboardShippingRoute
  '/livreur/finaliser': typeof AuthenticatedLivreurFinaliserRoute
  '/order/$id': typeof AuthenticatedOrderIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/livreur': typeof AuthenticatedLivreurIndexRoute
  '/client/facture/$id': typeof AuthenticatedClientFactureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/artisans': typeof ArtisansRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/logistics': typeof LogisticsRoute
  '/marketplace': typeof MarketplaceRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/tourism': typeof TourismRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/livreur': typeof AuthenticatedLivreurRouteRouteWithChildren
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/artisan/$id': typeof ArtisanIdRoute
  '/product/$id': typeof ProductIdRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/cron': typeof AuthenticatedAdminCronRoute
  '/_authenticated/admin/hubs': typeof AuthenticatedAdminHubsRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/shipping': typeof AuthenticatedAdminShippingRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/artisan/qr-code': typeof AuthenticatedArtisanQrCodeRoute
  '/_authenticated/artisan/revenus': typeof AuthenticatedArtisanRevenusRoute
  '/_authenticated/dashboard/b2b': typeof AuthenticatedDashboardB2bRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/payouts': typeof AuthenticatedDashboardPayoutsRoute
  '/_authenticated/dashboard/products': typeof AuthenticatedDashboardProductsRoute
  '/_authenticated/dashboard/promotions': typeof AuthenticatedDashboardPromotionsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/shipping': typeof AuthenticatedDashboardShippingRoute
  '/_authenticated/livreur/finaliser': typeof AuthenticatedLivreurFinaliserRoute
  '/_authenticated/order/$id': typeof AuthenticatedOrderIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/livreur/': typeof AuthenticatedLivreurIndexRoute
  '/_authenticated/client/facture/$id': typeof AuthenticatedClientFactureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai'
    | '/artisans'
    | '/auth'
    | '/b2b'
    | '/blog'
    | '/contact'
    | '/forgot-password'
    | '/logistics'
    | '/marketplace'
    | '/notifications'
    | '/pricing'
    | '/reset-password'
    | '/support'
    | '/tourism'
    | '/admin'
    | '/dashboard'
    | '/livreur'
    | '/cart'
    | '/checkout'
    | '/manager'
    | '/orders'
    | '/profile'
    | '/artisan/$id'
    | '/product/$id'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/cron'
    | '/admin/hubs'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/paiements'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/shipping'
    | '/admin/users'
    | '/artisan/qr-code'
    | '/artisan/revenus'
    | '/dashboard/b2b'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/products'
    | '/dashboard/promotions'
    | '/dashboard/settings'
    | '/dashboard/shipping'
    | '/livreur/finaliser'
    | '/order/$id'
    | '/admin/'
    | '/dashboard/'
    | '/livreur/'
    | '/client/facture/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai'
    | '/artisans'
    | '/auth'
    | '/b2b'
    | '/blog'
    | '/contact'
    | '/forgot-password'
    | '/logistics'
    | '/marketplace'
    | '/notifications'
    | '/pricing'
    | '/reset-password'
    | '/support'
    | '/tourism'
    | '/cart'
    | '/checkout'
    | '/manager'
    | '/orders'
    | '/profile'
    | '/artisan/$id'
    | '/product/$id'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/cron'
    | '/admin/hubs'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/paiements'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/shipping'
    | '/admin/users'
    | '/artisan/qr-code'
    | '/artisan/revenus'
    | '/dashboard/b2b'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/products'
    | '/dashboard/promotions'
    | '/dashboard/settings'
    | '/dashboard/shipping'
    | '/livreur/finaliser'
    | '/order/$id'
    | '/admin'
    | '/dashboard'
    | '/livreur'
    | '/client/facture/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ai'
    | '/artisans'
    | '/auth'
    | '/b2b'
    | '/blog'
    | '/contact'
    | '/forgot-password'
    | '/logistics'
    | '/marketplace'
    | '/notifications'
    | '/pricing'
    | '/reset-password'
    | '/support'
    | '/tourism'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/livreur'
    | '/_authenticated/cart'
    | '/_authenticated/checkout'
    | '/_authenticated/manager'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/artisan/$id'
    | '/product/$id'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/cron'
    | '/_authenticated/admin/hubs'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/paiements'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/shipping'
    | '/_authenticated/admin/users'
    | '/_authenticated/artisan/qr-code'
    | '/_authenticated/artisan/revenus'
    | '/_authenticated/dashboard/b2b'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/payouts'
    | '/_authenticated/dashboard/products'
    | '/_authenticated/dashboard/promotions'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/shipping'
    | '/_authenticated/livreur/finaliser'
    | '/_authenticated/order/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/livreur/'
    | '/_authenticated/client/facture/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AiRoute: typeof AiRoute
  ArtisansRoute: typeof ArtisansRoute
  AuthRoute: typeof AuthRoute
  B2bRoute: typeof B2bRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LogisticsRoute: typeof LogisticsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  TourismRoute: typeof TourismRoute
  ArtisanIdRoute: typeof ArtisanIdRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tourism': {
      id: '/tourism'
      path: '/tourism'
      fullPath: '/tourism'
      preLoaderRoute: typeof TourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisans': {
      id: '/artisans'
      path: '/artisans'
      fullPath: '/artisans'
      preLoaderRoute: typeof ArtisansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/$id': {
      id: '/artisan/$id'
      path: '/artisan/$id'
      fullPath: '/artisan/$id'
      preLoaderRoute: typeof ArtisanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livreur': {
      id: '/_authenticated/livreur'
      path: '/livreur'
      fullPath: '/livreur'
      preLoaderRoute: typeof AuthenticatedLivreurRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livreur/': {
      id: '/_authenticated/livreur/'
      path: '/'
      fullPath: '/livreur/'
      preLoaderRoute: typeof AuthenticatedLivreurIndexRouteImport
      parentRoute: typeof AuthenticatedLivreurRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/order/$id': {
      id: '/_authenticated/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof AuthenticatedOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livreur/finaliser': {
      id: '/_authenticated/livreur/finaliser'
      path: '/finaliser'
      fullPath: '/livreur/finaliser'
      preLoaderRoute: typeof AuthenticatedLivreurFinaliserRouteImport
      parentRoute: typeof AuthenticatedLivreurRouteRoute
    }
    '/_authenticated/dashboard/shipping': {
      id: '/_authenticated/dashboard/shipping'
      path: '/shipping'
      fullPath: '/dashboard/shipping'
      preLoaderRoute: typeof AuthenticatedDashboardShippingRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/promotions': {
      id: '/_authenticated/dashboard/promotions'
      path: '/promotions'
      fullPath: '/dashboard/promotions'
      preLoaderRoute: typeof AuthenticatedDashboardPromotionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/products': {
      id: '/_authenticated/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof AuthenticatedDashboardProductsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/payouts': {
      id: '/_authenticated/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof AuthenticatedDashboardPayoutsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/b2b': {
      id: '/_authenticated/dashboard/b2b'
      path: '/b2b'
      fullPath: '/dashboard/b2b'
      preLoaderRoute: typeof AuthenticatedDashboardB2bRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/artisan/revenus': {
      id: '/_authenticated/artisan/revenus'
      path: '/artisan/revenus'
      fullPath: '/artisan/revenus'
      preLoaderRoute: typeof AuthenticatedArtisanRevenusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artisan/qr-code': {
      id: '/_authenticated/artisan/qr-code'
      path: '/artisan/qr-code'
      fullPath: '/artisan/qr-code'
      preLoaderRoute: typeof AuthenticatedArtisanQrCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/shipping': {
      id: '/_authenticated/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AuthenticatedAdminShippingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/paiements': {
      id: '/_authenticated/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AuthenticatedAdminPaiementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hubs': {
      id: '/_authenticated/admin/hubs'
      path: '/hubs'
      fullPath: '/admin/hubs'
      preLoaderRoute: typeof AuthenticatedAdminHubsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cron': {
      id: '/_authenticated/admin/cron'
      path: '/cron'
      fullPath: '/admin/cron'
      preLoaderRoute: typeof AuthenticatedAdminCronRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/client/facture/$id': {
      id: '/_authenticated/client/facture/$id'
      path: '/client/facture/$id'
      fullPath: '/client/facture/$id'
      preLoaderRoute: typeof AuthenticatedClientFactureIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCronRoute: typeof AuthenticatedAdminCronRoute
  AuthenticatedAdminHubsRoute: typeof AuthenticatedAdminHubsRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPaiementsRoute: typeof AuthenticatedAdminPaiementsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminShippingRoute: typeof AuthenticatedAdminShippingRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminCronRoute: AuthenticatedAdminCronRoute,
    AuthenticatedAdminHubsRoute: AuthenticatedAdminHubsRoute,
    AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminPaiementsRoute: AuthenticatedAdminPaiementsRoute,
    AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
    AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
    AuthenticatedAdminShippingRoute: AuthenticatedAdminShippingRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardB2bRoute: typeof AuthenticatedDashboardB2bRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardPayoutsRoute: typeof AuthenticatedDashboardPayoutsRoute
  AuthenticatedDashboardProductsRoute: typeof AuthenticatedDashboardProductsRoute
  AuthenticatedDashboardPromotionsRoute: typeof AuthenticatedDashboardPromotionsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardShippingRoute: typeof AuthenticatedDashboardShippingRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardB2bRoute: AuthenticatedDashboardB2bRoute,
    AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
    AuthenticatedDashboardPayoutsRoute: AuthenticatedDashboardPayoutsRoute,
    AuthenticatedDashboardProductsRoute: AuthenticatedDashboardProductsRoute,
    AuthenticatedDashboardPromotionsRoute:
      AuthenticatedDashboardPromotionsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardShippingRoute: AuthenticatedDashboardShippingRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedLivreurRouteRouteChildren {
  AuthenticatedLivreurFinaliserRoute: typeof AuthenticatedLivreurFinaliserRoute
  AuthenticatedLivreurIndexRoute: typeof AuthenticatedLivreurIndexRoute
}

const AuthenticatedLivreurRouteRouteChildren: AuthenticatedLivreurRouteRouteChildren =
  {
    AuthenticatedLivreurFinaliserRoute: AuthenticatedLivreurFinaliserRoute,
    AuthenticatedLivreurIndexRoute: AuthenticatedLivreurIndexRoute,
  }

const AuthenticatedLivreurRouteRouteWithChildren =
  AuthenticatedLivreurRouteRoute._addFileChildren(
    AuthenticatedLivreurRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedLivreurRouteRoute: typeof AuthenticatedLivreurRouteRouteWithChildren
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedArtisanQrCodeRoute: typeof AuthenticatedArtisanQrCodeRoute
  AuthenticatedArtisanRevenusRoute: typeof AuthenticatedArtisanRevenusRoute
  AuthenticatedOrderIdRoute: typeof AuthenticatedOrderIdRoute
  AuthenticatedClientFactureIdRoute: typeof AuthenticatedClientFactureIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedLivreurRouteRoute: AuthenticatedLivreurRouteRouteWithChildren,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedArtisanQrCodeRoute: AuthenticatedArtisanQrCodeRoute,
  AuthenticatedArtisanRevenusRoute: AuthenticatedArtisanRevenusRoute,
  AuthenticatedOrderIdRoute: AuthenticatedOrderIdRoute,
  AuthenticatedClientFactureIdRoute: AuthenticatedClientFactureIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AiRoute: AiRoute,
  ArtisansRoute: ArtisansRoute,
  AuthRoute: AuthRoute,
  B2bRoute: B2bRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LogisticsRoute: LogisticsRoute,
  MarketplaceRoute: MarketplaceRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  TourismRoute: TourismRoute,
  ArtisanIdRoute: ArtisanIdRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
