// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    console.warn(`[Supabase] Missing ${missing.join(', ')} — running without Supabase (DB_MODE=local). Auth features disabled.`);
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

const _noopResult = Promise.resolve({ data: null, error: null });

function _noopQueryBuilder() {
  const builder: Record<string, any> = {
    select: () => builder,
    insert: () => builder,
    update: () => builder,
    delete: () => builder,
    eq: () => builder,
    order: () => builder,
    limit: () => builder,
    single: () => builder,
    maybeSingle: () => builder,
    gte: () => builder,
    lte: () => builder,
    in: () => builder,
    not: () => builder,
    or: () => builder,
    match: () => builder,
    filter: () => builder,
    contains: () => builder,
    containedBy: () => builder,
    range: () => builder,
    returns: () => builder,
    csv: () => builder,
    throwOnError: () => builder,
    abortSignal: () => builder,
    then: _noopResult.then.bind(_noopResult),
    catch: _noopResult.catch.bind(_noopResult),
    finally: _noopResult.finally.bind(_noopResult),
  };
  return builder;
}

function createNoopClient(): ReturnType<typeof createClient<Database>> {
  return {
    auth: {
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      getSession: () => _noopResult,
      getUser: () => _noopResult,
      signUp: () => _noopResult,
      signInWithPassword: () => _noopResult,
      signInWithOAuth: () => _noopResult,
      signOut: () => _noopResult,
      resetPasswordForEmail: () => _noopResult,
      updateUser: () => _noopResult,
      getClaims: () => _noopResult,
      verifyOtp: () => _noopResult,
      refreshSession: () => _noopResult,
      setSession: () => _noopResult,
    },
    from: () => _noopQueryBuilder(),
    rpc: () => _noopResult,
    channel: () => ({ on: () => ({ subscribe: () => ({ unsubscribe: () => {} }) }) }),
    schema: () => ({ from: () => _noopQueryBuilder() }),
    realtime: { subscribe: () => ({ unsubscribe: () => {} }) },
  } as ReturnType<typeof createClient<Database>>;
}

let _supabase: ReturnType<typeof createSupabaseClient> | null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    if (!_supabase) {
      _supabase = createNoopClient();
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});

